config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :emotions
    end
  end

  resources :users
  resources :sessions
  resources :emotions, except: :destroy
  resources :categories, only: [:index]

  root to: 'emoji#menu'
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  before_create :generate_access_token

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :emotions

  validates_presence_of :name
  validates :name, inclusion: { in: %w(positive negative), message: 'Not a valid
                                category'}
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :recognize, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :emotions

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/api/v1/emotions_controller.rb
module Api
  module V1
    class EmotionsController < ApplicationController
      before_filter :restrict_access

      def create
        @emotion = Product.create(emotion_params)
        render @emotion
      end

      def index
        @emotions =  current_user.present? ? current_user.emotions : Emotion.all
        render @emotions
      end

      def show
        @emotion =  Emotion.find(params[:id])

        render @emotion
      end

      def update
        @emotion = Emotion.update(params[:id], emotions_params)
        render @emotion
      end

      private
      def emotion_params
        params.require(:emotion).permit(:recognize, :category_id, :user_id,
                                        :investigation, :action_item, :current)
      end

      def restrict_access
        authenticate_or_request_with_http_token do |token, options|
          ApiKey.exists?(access_token: token)
        end
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::MimeResponds
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert:"Not authorized" if current_user.nil?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @emotion = Emotion.new
    @categories = Category.all
  end

end

app/controllers/emoji_controller.rb
class EmojiController < ApplicationController
  before_filter :authorize, only: [:edit, :update]

  def menu
    @emotions = Emotion.all.sample(3)
  end
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  def new
    @emotion = Emotion.new
  end

  def create
    @emotion = Emotion.new(emotion_params)
    if @emotion.save
      redirect_to emotions_path
    else
      render "new"
    end

  end

  def index
    @emotions = current_user.emotions
  end

  def edit
    @emotion = Emotion.find(params[:id])
  end

  def update
    @emotion = Emotion.find(params[:id])
    if @emotion.update_attributes(emotion_params)
      redirect_to emotions_path
    else
      render "edit"
    end

  end

  private
  def emotion_params
    params.require(:emotion).permit(:recognize, :category_id, :user_id,
                                    :investigation, :action_item, :current)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to categories_path
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:usesr_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.haml
- if current_user
  .row
    %br
    .col.s12.m4.offset-m5.menu
      - @categories.each do |c|
        %p
          =link_to new_emotion_path(category_id: c.id) do
            - if c.name == "positive"
              %i.menu-icon.fa.fa-heart(aria-hidden = "true")
              Positive
            - else
              %i.menu-icon.fa.fa-heart-o(aria-hidden = "true")
              Needs Love
      %p
        =link_to emotions_path() do
          %i.menu-icon.fa.fa-tint(aria-hidden = "true")
          My Emotions

app/views/emoji/menu.html.haml
.row
  .col.s12.m10.offset-m1
    %p.center-align
      How is Our Community Feeling?
    .emotion-snippets
      - @emotions.each do |e|
        %p.center-align
          =e.recognize
    %br
.row
  .col.s12.m3.offset-m9.reminder
    reflect. &
    %b
      give yourself a break.
.row
  -if current_user.present? && ApiKey.find(current_user.id).present?
    %small
      Access Token:
      =ApiKey.find(current_user.id).access_token

app/views/emotions/_form.html.haml
.row
  .col.s12.m10.offset-m1
    = form_for @emotion do |e|
      = e.hidden_field :category_id, value: @emotion.category_id || params[:category_id]
      = e.hidden_field :user_id, value: current_user.id
      .input-field
        = e.text_field :recognize, placeholder: 'How are you?'
      - unless @emotion.new_record?
        .input-field
          = e.text_field :investigation
          %label
            Let's Investigate.  What unmet need requires attn?
        .input-field
          = e.text_field :action_item
          %label
            Where do you go from here?
        = e.check_box :current, checked: @emotion.current?
        = e.label :current, "Yes, this is present in my life."
      %br
      .right
        .row
          .col.s3.offset-s1
            %small
              = link_to "Cancel", emotions_path()
          .col.s4
            = e.submit "Acknowledge"

app/views/emotions/edit.html.haml
=render :partial => '/emotions/form', :object => @emotion

app/views/emotions/index.html.haml
.row
  .col.s10.offset-s1
    - @emotions.each do |e|
      %p
        - if Category.find(e.category_id).name == "positive"
          %i.fa.fa-heart
        - else
          %i.fa.fa-heart-o
        = e.recognize
        %span.magnify
          = link_to edit_emotion_path(e) do
            %i.fa.fa-search

app/views/emotions/new.html.haml
=render :partial => '/emotions/form', :locals => {:category_id => params[:category_id]}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mara
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    %link(rel = "stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css")
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    %script(src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js")
    %script(src="https://use.fontawesome.com/d84584ad34.js")
  %body.brown.lighten-5
    .navbar-wrapper
      %nav.green.lighten-2
        .nav-wrapper
          .row
            .col.s6.m9
              %a#rain-logo.brand-logo.center(href = "/")
                %i.banner-raindrop.fa.fa-tint(aria-hidden = "true")
                Rain
            .col.s6.m3
              %span.right.nav-action
                - if current_user
                  = link_to "Log Out", logout_path
                - else
                  - if current_page?('/login')
                    = link_to "Sign Up", signup_path
                  - elsif current_page?('/signup')
                    = link_to "Log In", login_path
                  - else
                    = link_to "Sign Up", signup_path
                    or
                    = link_to "Log In", login_path

                - flash.each do |name, msg|
                  = content_tag :div, msg, id: "flash_#{name}"

    = yield

app/views/users/new.html.haml
.row
  .col.s12.l10.offset-l1
    %h4
      Sign Up

    = form_for @user do |f|
      - if @user.errors.any?
        .error_messages
          %h2
            Form is invalid
          %ul
            = @user.errors.full_messages.each do |message|
              %li
                =message

      .field
        = f.label :email
        %br
        = f.text_field :email

      .field
        = f.label :password
        %br
        = f.text_field :password

      .field
        = f.label :password_confirmation
        %br
        = f.text_field :password_confirmation

      .actions
        = f.submit